//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson()
        {
            this.studying = new HashSet<studying>();
        }
    
        public int id { get; set; }
        public string day_in_week { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public Nullable<int> classroom_id { get; set; }
        public Nullable<int> teaching_id { get; set; }
        public Nullable<int> class_module_id { get; set; }
    
        public virtual class_module class_module { get; set; }
        public virtual classroom classroom { get; set; }
        public virtual teaching teaching { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studying> studying { get; set; }
    }
}
