//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public int id { get; set; }
        public string day_in_week { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> classroom_id { get; set; }
        public Nullable<int> teaching_id { get; set; }
        public Nullable<int> class_module_id { get; set; }
        public Nullable<int> week_in_term_id { get; set; }
    
        public virtual class_module class_module { get; set; }
        public virtual classroom classroom { get; set; }
        public virtual teaching teaching { get; set; }
        public virtual week_in_term week_in_term { get; set; }
    }
}
