//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingManagementEntities : DbContext
    {
        public TrainingManagementEntities()
            : base("name=TrainingManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<class_module> class_module { get; set; }
        public virtual DbSet<classroom> classrooms { get; set; }
        public virtual DbSet<curriculum> curricula { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<major> majors { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studying> studyings { get; set; }
        public virtual DbSet<teaching> teachings { get; set; }
        public virtual DbSet<teaching_assignment> teaching_assignment { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
