//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public module()
        {
            this.class_module = new HashSet<class_module>();
            this.teaching_assignment = new HashSet<teaching_assignment>();
        }
    
        public int id { get; set; }
        public string ID_Module { get; set; }
        public string name { get; set; }
        public Nullable<int> theory_credits { get; set; }
        public Nullable<int> practice_credits { get; set; }
        public Nullable<int> self_study_credits { get; set; }
        public Nullable<int> visiting_credits { get; set; }
        public Nullable<int> curriculum_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_module> class_module { get; set; }
        public virtual curriculum curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teaching_assignment> teaching_assignment { get; set; }
    }
}
