//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class studying
    {
        public int id { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> lesson_id { get; set; }
    
        public virtual lesson lesson { get; set; }
        public virtual student student { get; set; }
    }
}
