//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class teaching_assignment
    {
        public int id { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> lecturer_id { get; set; }
    
        public virtual lecturer lecturer { get; set; }
        public virtual module module { get; set; }
    }
}
